<?php
/**
 * EdFiRestraintEvent
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Resources\Model;

use \ArrayAccess;
use \Resources\ObjectSerializer;

/**
 * EdFiRestraintEvent Class Doc Comment
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EdFiRestraintEvent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'edFi_restraintEvent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'restraint_event_identifier' => 'string',
        'discipline_incident_reference' => '\Resources\Model\EdFiDisciplineIncidentReference',
        'school_reference' => '\Resources\Model\EdFiSchoolReference',
        'student_reference' => '\Resources\Model\EdFiStudentReference',
        'educational_environment_descriptor' => 'string',
        'event_date' => '\DateTime',
        'programs' => '\Resources\Model\EdFiRestraintEventProgram[]',
        'reasons' => '\Resources\Model\EdFiRestraintEventReason[]',
        '_etag' => 'string',
        '_last_modified_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'restraint_event_identifier' => null,
        'discipline_incident_reference' => null,
        'school_reference' => null,
        'student_reference' => null,
        'educational_environment_descriptor' => null,
        'event_date' => 'date',
        'programs' => null,
        'reasons' => null,
        '_etag' => null,
        '_last_modified_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'restraint_event_identifier' => false,
        'discipline_incident_reference' => false,
        'school_reference' => false,
        'student_reference' => false,
        'educational_environment_descriptor' => true,
        'event_date' => false,
        'programs' => false,
        'reasons' => false,
        '_etag' => false,
        '_last_modified_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'restraint_event_identifier' => 'restraintEventIdentifier',
        'discipline_incident_reference' => 'disciplineIncidentReference',
        'school_reference' => 'schoolReference',
        'student_reference' => 'studentReference',
        'educational_environment_descriptor' => 'educationalEnvironmentDescriptor',
        'event_date' => 'eventDate',
        'programs' => 'programs',
        'reasons' => 'reasons',
        '_etag' => '_etag',
        '_last_modified_date' => '_lastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'restraint_event_identifier' => 'setRestraintEventIdentifier',
        'discipline_incident_reference' => 'setDisciplineIncidentReference',
        'school_reference' => 'setSchoolReference',
        'student_reference' => 'setStudentReference',
        'educational_environment_descriptor' => 'setEducationalEnvironmentDescriptor',
        'event_date' => 'setEventDate',
        'programs' => 'setPrograms',
        'reasons' => 'setReasons',
        '_etag' => 'setEtag',
        '_last_modified_date' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'restraint_event_identifier' => 'getRestraintEventIdentifier',
        'discipline_incident_reference' => 'getDisciplineIncidentReference',
        'school_reference' => 'getSchoolReference',
        'student_reference' => 'getStudentReference',
        'educational_environment_descriptor' => 'getEducationalEnvironmentDescriptor',
        'event_date' => 'getEventDate',
        'programs' => 'getPrograms',
        'reasons' => 'getReasons',
        '_etag' => 'getEtag',
        '_last_modified_date' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('restraint_event_identifier', $data ?? [], null);
        $this->setIfExists('discipline_incident_reference', $data ?? [], null);
        $this->setIfExists('school_reference', $data ?? [], null);
        $this->setIfExists('student_reference', $data ?? [], null);
        $this->setIfExists('educational_environment_descriptor', $data ?? [], null);
        $this->setIfExists('event_date', $data ?? [], null);
        $this->setIfExists('programs', $data ?? [], null);
        $this->setIfExists('reasons', $data ?? [], null);
        $this->setIfExists('_etag', $data ?? [], null);
        $this->setIfExists('_last_modified_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['restraint_event_identifier'] === null) {
            $invalidProperties[] = "'restraint_event_identifier' can't be null";
        }
        if ((mb_strlen($this->container['restraint_event_identifier']) > 36)) {
            $invalidProperties[] = "invalid value for 'restraint_event_identifier', the character length must be smaller than or equal to 36.";
        }

        if ($this->container['school_reference'] === null) {
            $invalidProperties[] = "'school_reference' can't be null";
        }
        if ($this->container['student_reference'] === null) {
            $invalidProperties[] = "'student_reference' can't be null";
        }
        if (!is_null($this->container['educational_environment_descriptor']) && (mb_strlen($this->container['educational_environment_descriptor']) > 306)) {
            $invalidProperties[] = "invalid value for 'educational_environment_descriptor', the character length must be smaller than or equal to 306.";
        }

        if ($this->container['event_date'] === null) {
            $invalidProperties[] = "'event_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id 
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets restraint_event_identifier
     *
     * @return string
     */
    public function getRestraintEventIdentifier()
    {
        return $this->container['restraint_event_identifier'];
    }

    /**
     * Sets restraint_event_identifier
     *
     * @param string $restraint_event_identifier A unique number or alphanumeric code assigned to a restraint event by a school, school system, state, or other agency or entity.
     *
     * @return self
     */
    public function setRestraintEventIdentifier($restraint_event_identifier)
    {
        if (is_null($restraint_event_identifier)) {
            throw new \InvalidArgumentException('non-nullable restraint_event_identifier cannot be null');
        }
        if ((mb_strlen($restraint_event_identifier) > 36)) {
            throw new \InvalidArgumentException('invalid length for $restraint_event_identifier when calling EdFiRestraintEvent., must be smaller than or equal to 36.');
        }

        $this->container['restraint_event_identifier'] = $restraint_event_identifier;

        return $this;
    }

    /**
     * Gets discipline_incident_reference
     *
     * @return \Resources\Model\EdFiDisciplineIncidentReference|null
     */
    public function getDisciplineIncidentReference()
    {
        return $this->container['discipline_incident_reference'];
    }

    /**
     * Sets discipline_incident_reference
     *
     * @param \Resources\Model\EdFiDisciplineIncidentReference|null $discipline_incident_reference discipline_incident_reference
     *
     * @return self
     */
    public function setDisciplineIncidentReference($discipline_incident_reference)
    {
        if (is_null($discipline_incident_reference)) {
            throw new \InvalidArgumentException('non-nullable discipline_incident_reference cannot be null');
        }
        $this->container['discipline_incident_reference'] = $discipline_incident_reference;

        return $this;
    }

    /**
     * Gets school_reference
     *
     * @return \Resources\Model\EdFiSchoolReference
     */
    public function getSchoolReference()
    {
        return $this->container['school_reference'];
    }

    /**
     * Sets school_reference
     *
     * @param \Resources\Model\EdFiSchoolReference $school_reference school_reference
     *
     * @return self
     */
    public function setSchoolReference($school_reference)
    {
        if (is_null($school_reference)) {
            throw new \InvalidArgumentException('non-nullable school_reference cannot be null');
        }
        $this->container['school_reference'] = $school_reference;

        return $this;
    }

    /**
     * Gets student_reference
     *
     * @return \Resources\Model\EdFiStudentReference
     */
    public function getStudentReference()
    {
        return $this->container['student_reference'];
    }

    /**
     * Sets student_reference
     *
     * @param \Resources\Model\EdFiStudentReference $student_reference student_reference
     *
     * @return self
     */
    public function setStudentReference($student_reference)
    {
        if (is_null($student_reference)) {
            throw new \InvalidArgumentException('non-nullable student_reference cannot be null');
        }
        $this->container['student_reference'] = $student_reference;

        return $this;
    }

    /**
     * Gets educational_environment_descriptor
     *
     * @return string|null
     */
    public function getEducationalEnvironmentDescriptor()
    {
        return $this->container['educational_environment_descriptor'];
    }

    /**
     * Sets educational_environment_descriptor
     *
     * @param string|null $educational_environment_descriptor The setting where the RestraintEvent was exercised.
     *
     * @return self
     */
    public function setEducationalEnvironmentDescriptor($educational_environment_descriptor)
    {
        if (is_null($educational_environment_descriptor)) {
            array_push($this->openAPINullablesSetToNull, 'educational_environment_descriptor');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('educational_environment_descriptor', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($educational_environment_descriptor) && (mb_strlen($educational_environment_descriptor) > 306)) {
            throw new \InvalidArgumentException('invalid length for $educational_environment_descriptor when calling EdFiRestraintEvent., must be smaller than or equal to 306.');
        }

        $this->container['educational_environment_descriptor'] = $educational_environment_descriptor;

        return $this;
    }

    /**
     * Gets event_date
     *
     * @return \DateTime
     */
    public function getEventDate()
    {
        return $this->container['event_date'];
    }

    /**
     * Sets event_date
     *
     * @param \DateTime $event_date Month, day, and year of the restraint event.
     *
     * @return self
     */
    public function setEventDate($event_date)
    {
        if (is_null($event_date)) {
            throw new \InvalidArgumentException('non-nullable event_date cannot be null');
        }
        $this->container['event_date'] = $event_date;

        return $this;
    }

    /**
     * Gets programs
     *
     * @return \Resources\Model\EdFiRestraintEventProgram[]|null
     */
    public function getPrograms()
    {
        return $this->container['programs'];
    }

    /**
     * Sets programs
     *
     * @param \Resources\Model\EdFiRestraintEventProgram[]|null $programs An unordered collection of restraintEventPrograms. The special education program associated with the restraint event.
     *
     * @return self
     */
    public function setPrograms($programs)
    {
        if (is_null($programs)) {
            throw new \InvalidArgumentException('non-nullable programs cannot be null');
        }
        $this->container['programs'] = $programs;

        return $this;
    }

    /**
     * Gets reasons
     *
     * @return \Resources\Model\EdFiRestraintEventReason[]|null
     */
    public function getReasons()
    {
        return $this->container['reasons'];
    }

    /**
     * Sets reasons
     *
     * @param \Resources\Model\EdFiRestraintEventReason[]|null $reasons An unordered collection of restraintEventReasons. A categorization of the circumstances or reason for the RestraintEvent.
     *
     * @return self
     */
    public function setReasons($reasons)
    {
        if (is_null($reasons)) {
            throw new \InvalidArgumentException('non-nullable reasons cannot be null');
        }
        $this->container['reasons'] = $reasons;

        return $this;
    }

    /**
     * Gets _etag
     *
     * @return string|null
     */
    public function getEtag()
    {
        return $this->container['_etag'];
    }

    /**
     * Sets _etag
     *
     * @param string|null $_etag A unique system-generated value that identifies the version of the resource.
     *
     * @return self
     */
    public function setEtag($_etag)
    {
        if (is_null($_etag)) {
            throw new \InvalidArgumentException('non-nullable _etag cannot be null');
        }
        $this->container['_etag'] = $_etag;

        return $this;
    }

    /**
     * Gets _last_modified_date
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['_last_modified_date'];
    }

    /**
     * Sets _last_modified_date
     *
     * @param \DateTime|null $_last_modified_date The date and time the resource was last modified.
     *
     * @return self
     */
    public function setLastModifiedDate($_last_modified_date)
    {
        if (is_null($_last_modified_date)) {
            throw new \InvalidArgumentException('non-nullable _last_modified_date cannot be null');
        }
        $this->container['_last_modified_date'] = $_last_modified_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


