<?php
/**
 * EdFiLocation
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EdFiLocation Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EdFiLocation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'edFi_location';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'classroom_identification_code' => 'string',
        'school_reference' => '\OpenAPI\Client\Model\EdFiSchoolReference',
        'maximum_number_of_seats' => 'int',
        'optimal_number_of_seats' => 'int',
        '_etag' => 'string',
        '_last_modified_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'classroom_identification_code' => null,
        'school_reference' => null,
        'maximum_number_of_seats' => 'int32',
        'optimal_number_of_seats' => 'int32',
        '_etag' => null,
        '_last_modified_date' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'classroom_identification_code' => 'classroomIdentificationCode',
        'school_reference' => 'schoolReference',
        'maximum_number_of_seats' => 'maximumNumberOfSeats',
        'optimal_number_of_seats' => 'optimalNumberOfSeats',
        '_etag' => '_etag',
        '_last_modified_date' => '_lastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'classroom_identification_code' => 'setClassroomIdentificationCode',
        'school_reference' => 'setSchoolReference',
        'maximum_number_of_seats' => 'setMaximumNumberOfSeats',
        'optimal_number_of_seats' => 'setOptimalNumberOfSeats',
        '_etag' => 'setEtag',
        '_last_modified_date' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'classroom_identification_code' => 'getClassroomIdentificationCode',
        'school_reference' => 'getSchoolReference',
        'maximum_number_of_seats' => 'getMaximumNumberOfSeats',
        'optimal_number_of_seats' => 'getOptimalNumberOfSeats',
        '_etag' => 'getEtag',
        '_last_modified_date' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['classroom_identification_code'] = $data['classroom_identification_code'] ?? null;
        $this->container['school_reference'] = $data['school_reference'] ?? null;
        $this->container['maximum_number_of_seats'] = $data['maximum_number_of_seats'] ?? null;
        $this->container['optimal_number_of_seats'] = $data['optimal_number_of_seats'] ?? null;
        $this->container['_etag'] = $data['_etag'] ?? null;
        $this->container['_last_modified_date'] = $data['_last_modified_date'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['classroom_identification_code'] === null) {
            $invalidProperties[] = "'classroom_identification_code' can't be null";
        }
        if ((mb_strlen($this->container['classroom_identification_code']) > 60)) {
            $invalidProperties[] = "invalid value for 'classroom_identification_code', the character length must be smaller than or equal to 60.";
        }

        if ((mb_strlen($this->container['classroom_identification_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'classroom_identification_code', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['school_reference'] === null) {
            $invalidProperties[] = "'school_reference' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets classroom_identification_code
     *
     * @return string
     */
    public function getClassroomIdentificationCode()
    {
        return $this->container['classroom_identification_code'];
    }

    /**
     * Sets classroom_identification_code
     *
     * @param string $classroom_identification_code A unique number or alphanumeric code assigned to a room by a school, school system, state, or other agency or entity.
     *
     * @return self
     */
    public function setClassroomIdentificationCode($classroom_identification_code)
    {
        if ((mb_strlen($classroom_identification_code) > 60)) {
            throw new \InvalidArgumentException('invalid length for $classroom_identification_code when calling EdFiLocation., must be smaller than or equal to 60.');
        }
        if ((mb_strlen($classroom_identification_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $classroom_identification_code when calling EdFiLocation., must be bigger than or equal to 1.');
        }

        $this->container['classroom_identification_code'] = $classroom_identification_code;

        return $this;
    }

    /**
     * Gets school_reference
     *
     * @return \OpenAPI\Client\Model\EdFiSchoolReference
     */
    public function getSchoolReference()
    {
        return $this->container['school_reference'];
    }

    /**
     * Sets school_reference
     *
     * @param \OpenAPI\Client\Model\EdFiSchoolReference $school_reference school_reference
     *
     * @return self
     */
    public function setSchoolReference($school_reference)
    {
        $this->container['school_reference'] = $school_reference;

        return $this;
    }

    /**
     * Gets maximum_number_of_seats
     *
     * @return int|null
     */
    public function getMaximumNumberOfSeats()
    {
        return $this->container['maximum_number_of_seats'];
    }

    /**
     * Sets maximum_number_of_seats
     *
     * @param int|null $maximum_number_of_seats The most number of seats the class can maintain.
     *
     * @return self
     */
    public function setMaximumNumberOfSeats($maximum_number_of_seats)
    {
        $this->container['maximum_number_of_seats'] = $maximum_number_of_seats;

        return $this;
    }

    /**
     * Gets optimal_number_of_seats
     *
     * @return int|null
     */
    public function getOptimalNumberOfSeats()
    {
        return $this->container['optimal_number_of_seats'];
    }

    /**
     * Sets optimal_number_of_seats
     *
     * @param int|null $optimal_number_of_seats The number of seats that is most favorable to the class.
     *
     * @return self
     */
    public function setOptimalNumberOfSeats($optimal_number_of_seats)
    {
        $this->container['optimal_number_of_seats'] = $optimal_number_of_seats;

        return $this;
    }

    /**
     * Gets _etag
     *
     * @return string|null
     */
    public function getEtag()
    {
        return $this->container['_etag'];
    }

    /**
     * Sets _etag
     *
     * @param string|null $_etag A unique system-generated value that identifies the version of the resource.
     *
     * @return self
     */
    public function setEtag($_etag)
    {
        $this->container['_etag'] = $_etag;

        return $this;
    }

    /**
     * Gets _last_modified_date
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['_last_modified_date'];
    }

    /**
     * Sets _last_modified_date
     *
     * @param \DateTime|null $_last_modified_date The date and time the resource was last modified.
     *
     * @return self
     */
    public function setLastModifiedDate($_last_modified_date)
    {
        $this->container['_last_modified_date'] = $_last_modified_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


