<?php
/**
 * EdFiEvaluationRubricDimension
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EdFiEvaluationRubricDimension Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EdFiEvaluationRubricDimension implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'edFi_evaluationRubricDimension';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'evaluation_rubric_rating' => 'int',
        'program_evaluation_element_reference' => '\OpenAPI\Client\Model\EdFiProgramEvaluationElementReference',
        'evaluation_criterion_description' => 'string',
        'evaluation_rubric_rating_level_descriptor' => 'string',
        'rubric_dimension_sort_order' => 'int',
        '_etag' => 'string',
        '_last_modified_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'evaluation_rubric_rating' => 'int32',
        'program_evaluation_element_reference' => null,
        'evaluation_criterion_description' => null,
        'evaluation_rubric_rating_level_descriptor' => null,
        'rubric_dimension_sort_order' => 'int32',
        '_etag' => null,
        '_last_modified_date' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'evaluation_rubric_rating' => 'evaluationRubricRating',
        'program_evaluation_element_reference' => 'programEvaluationElementReference',
        'evaluation_criterion_description' => 'evaluationCriterionDescription',
        'evaluation_rubric_rating_level_descriptor' => 'evaluationRubricRatingLevelDescriptor',
        'rubric_dimension_sort_order' => 'rubricDimensionSortOrder',
        '_etag' => '_etag',
        '_last_modified_date' => '_lastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'evaluation_rubric_rating' => 'setEvaluationRubricRating',
        'program_evaluation_element_reference' => 'setProgramEvaluationElementReference',
        'evaluation_criterion_description' => 'setEvaluationCriterionDescription',
        'evaluation_rubric_rating_level_descriptor' => 'setEvaluationRubricRatingLevelDescriptor',
        'rubric_dimension_sort_order' => 'setRubricDimensionSortOrder',
        '_etag' => 'setEtag',
        '_last_modified_date' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'evaluation_rubric_rating' => 'getEvaluationRubricRating',
        'program_evaluation_element_reference' => 'getProgramEvaluationElementReference',
        'evaluation_criterion_description' => 'getEvaluationCriterionDescription',
        'evaluation_rubric_rating_level_descriptor' => 'getEvaluationRubricRatingLevelDescriptor',
        'rubric_dimension_sort_order' => 'getRubricDimensionSortOrder',
        '_etag' => 'getEtag',
        '_last_modified_date' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['evaluation_rubric_rating'] = $data['evaluation_rubric_rating'] ?? null;
        $this->container['program_evaluation_element_reference'] = $data['program_evaluation_element_reference'] ?? null;
        $this->container['evaluation_criterion_description'] = $data['evaluation_criterion_description'] ?? null;
        $this->container['evaluation_rubric_rating_level_descriptor'] = $data['evaluation_rubric_rating_level_descriptor'] ?? null;
        $this->container['rubric_dimension_sort_order'] = $data['rubric_dimension_sort_order'] ?? null;
        $this->container['_etag'] = $data['_etag'] ?? null;
        $this->container['_last_modified_date'] = $data['_last_modified_date'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['evaluation_rubric_rating'] === null) {
            $invalidProperties[] = "'evaluation_rubric_rating' can't be null";
        }
        if ($this->container['program_evaluation_element_reference'] === null) {
            $invalidProperties[] = "'program_evaluation_element_reference' can't be null";
        }
        if ($this->container['evaluation_criterion_description'] === null) {
            $invalidProperties[] = "'evaluation_criterion_description' can't be null";
        }
        if ((mb_strlen($this->container['evaluation_criterion_description']) > 1024)) {
            $invalidProperties[] = "invalid value for 'evaluation_criterion_description', the character length must be smaller than or equal to 1024.";
        }

        if ((mb_strlen($this->container['evaluation_criterion_description']) < 1)) {
            $invalidProperties[] = "invalid value for 'evaluation_criterion_description', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['evaluation_rubric_rating_level_descriptor']) && (mb_strlen($this->container['evaluation_rubric_rating_level_descriptor']) > 306)) {
            $invalidProperties[] = "invalid value for 'evaluation_rubric_rating_level_descriptor', the character length must be smaller than or equal to 306.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets evaluation_rubric_rating
     *
     * @return int
     */
    public function getEvaluationRubricRating()
    {
        return $this->container['evaluation_rubric_rating'];
    }

    /**
     * Sets evaluation_rubric_rating
     *
     * @param int $evaluation_rubric_rating The numeric rating associated with the evaluation rubric dimension.
     *
     * @return self
     */
    public function setEvaluationRubricRating($evaluation_rubric_rating)
    {
        $this->container['evaluation_rubric_rating'] = $evaluation_rubric_rating;

        return $this;
    }

    /**
     * Gets program_evaluation_element_reference
     *
     * @return \OpenAPI\Client\Model\EdFiProgramEvaluationElementReference
     */
    public function getProgramEvaluationElementReference()
    {
        return $this->container['program_evaluation_element_reference'];
    }

    /**
     * Sets program_evaluation_element_reference
     *
     * @param \OpenAPI\Client\Model\EdFiProgramEvaluationElementReference $program_evaluation_element_reference program_evaluation_element_reference
     *
     * @return self
     */
    public function setProgramEvaluationElementReference($program_evaluation_element_reference)
    {
        $this->container['program_evaluation_element_reference'] = $program_evaluation_element_reference;

        return $this;
    }

    /**
     * Gets evaluation_criterion_description
     *
     * @return string
     */
    public function getEvaluationCriterionDescription()
    {
        return $this->container['evaluation_criterion_description'];
    }

    /**
     * Sets evaluation_criterion_description
     *
     * @param string $evaluation_criterion_description The evaluation criterion description for the evaluation rubric dimension.
     *
     * @return self
     */
    public function setEvaluationCriterionDescription($evaluation_criterion_description)
    {
        if ((mb_strlen($evaluation_criterion_description) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_criterion_description when calling EdFiEvaluationRubricDimension., must be smaller than or equal to 1024.');
        }
        if ((mb_strlen($evaluation_criterion_description) < 1)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_criterion_description when calling EdFiEvaluationRubricDimension., must be bigger than or equal to 1.');
        }

        $this->container['evaluation_criterion_description'] = $evaluation_criterion_description;

        return $this;
    }

    /**
     * Gets evaluation_rubric_rating_level_descriptor
     *
     * @return string|null
     */
    public function getEvaluationRubricRatingLevelDescriptor()
    {
        return $this->container['evaluation_rubric_rating_level_descriptor'];
    }

    /**
     * Sets evaluation_rubric_rating_level_descriptor
     *
     * @param string|null $evaluation_rubric_rating_level_descriptor The rating level achieved for the evaluation rubric dimension.
     *
     * @return self
     */
    public function setEvaluationRubricRatingLevelDescriptor($evaluation_rubric_rating_level_descriptor)
    {
        if (!is_null($evaluation_rubric_rating_level_descriptor) && (mb_strlen($evaluation_rubric_rating_level_descriptor) > 306)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_rubric_rating_level_descriptor when calling EdFiEvaluationRubricDimension., must be smaller than or equal to 306.');
        }

        $this->container['evaluation_rubric_rating_level_descriptor'] = $evaluation_rubric_rating_level_descriptor;

        return $this;
    }

    /**
     * Gets rubric_dimension_sort_order
     *
     * @return int|null
     */
    public function getRubricDimensionSortOrder()
    {
        return $this->container['rubric_dimension_sort_order'];
    }

    /**
     * Sets rubric_dimension_sort_order
     *
     * @param int|null $rubric_dimension_sort_order The sort order of the rubric dimension.
     *
     * @return self
     */
    public function setRubricDimensionSortOrder($rubric_dimension_sort_order)
    {
        $this->container['rubric_dimension_sort_order'] = $rubric_dimension_sort_order;

        return $this;
    }

    /**
     * Gets _etag
     *
     * @return string|null
     */
    public function getEtag()
    {
        return $this->container['_etag'];
    }

    /**
     * Sets _etag
     *
     * @param string|null $_etag A unique system-generated value that identifies the version of the resource.
     *
     * @return self
     */
    public function setEtag($_etag)
    {
        $this->container['_etag'] = $_etag;

        return $this;
    }

    /**
     * Gets _last_modified_date
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['_last_modified_date'];
    }

    /**
     * Sets _last_modified_date
     *
     * @param \DateTime|null $_last_modified_date The date and time the resource was last modified.
     *
     * @return self
     */
    public function setLastModifiedDate($_last_modified_date)
    {
        $this->container['_last_modified_date'] = $_last_modified_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


