<?php
/**
 * EdFiCourseTranscriptAlternativeCourseIdentificationCode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EdFiCourseTranscriptAlternativeCourseIdentificationCode Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EdFiCourseTranscriptAlternativeCourseIdentificationCode implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'edFi_courseTranscriptAlternativeCourseIdentificationCode';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'course_identification_system_descriptor' => 'string',
        'assigning_organization_identification_code' => 'string',
        'course_catalog_url' => 'string',
        'identification_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'course_identification_system_descriptor' => null,
        'assigning_organization_identification_code' => null,
        'course_catalog_url' => null,
        'identification_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'course_identification_system_descriptor' => false,
        'assigning_organization_identification_code' => true,
        'course_catalog_url' => true,
        'identification_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'course_identification_system_descriptor' => 'courseIdentificationSystemDescriptor',
        'assigning_organization_identification_code' => 'assigningOrganizationIdentificationCode',
        'course_catalog_url' => 'courseCatalogURL',
        'identification_code' => 'identificationCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'course_identification_system_descriptor' => 'setCourseIdentificationSystemDescriptor',
        'assigning_organization_identification_code' => 'setAssigningOrganizationIdentificationCode',
        'course_catalog_url' => 'setCourseCatalogUrl',
        'identification_code' => 'setIdentificationCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'course_identification_system_descriptor' => 'getCourseIdentificationSystemDescriptor',
        'assigning_organization_identification_code' => 'getAssigningOrganizationIdentificationCode',
        'course_catalog_url' => 'getCourseCatalogUrl',
        'identification_code' => 'getIdentificationCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('course_identification_system_descriptor', $data ?? [], null);
        $this->setIfExists('assigning_organization_identification_code', $data ?? [], null);
        $this->setIfExists('course_catalog_url', $data ?? [], null);
        $this->setIfExists('identification_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['course_identification_system_descriptor'] === null) {
            $invalidProperties[] = "'course_identification_system_descriptor' can't be null";
        }
        if ((mb_strlen($this->container['course_identification_system_descriptor']) > 306)) {
            $invalidProperties[] = "invalid value for 'course_identification_system_descriptor', the character length must be smaller than or equal to 306.";
        }

        if (!is_null($this->container['assigning_organization_identification_code']) && (mb_strlen($this->container['assigning_organization_identification_code']) > 60)) {
            $invalidProperties[] = "invalid value for 'assigning_organization_identification_code', the character length must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['assigning_organization_identification_code']) && (mb_strlen($this->container['assigning_organization_identification_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'assigning_organization_identification_code', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['course_catalog_url']) && (mb_strlen($this->container['course_catalog_url']) > 255)) {
            $invalidProperties[] = "invalid value for 'course_catalog_url', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['course_catalog_url']) && (mb_strlen($this->container['course_catalog_url']) < 5)) {
            $invalidProperties[] = "invalid value for 'course_catalog_url', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['identification_code'] === null) {
            $invalidProperties[] = "'identification_code' can't be null";
        }
        if ((mb_strlen($this->container['identification_code']) > 60)) {
            $invalidProperties[] = "invalid value for 'identification_code', the character length must be smaller than or equal to 60.";
        }

        if ((mb_strlen($this->container['identification_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'identification_code', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets course_identification_system_descriptor
     *
     * @return string
     */
    public function getCourseIdentificationSystemDescriptor()
    {
        return $this->container['course_identification_system_descriptor'];
    }

    /**
     * Sets course_identification_system_descriptor
     *
     * @param string $course_identification_system_descriptor A system that is used to identify the organization of subject matter and related learning experiences provided for the instruction of students.
     *
     * @return self
     */
    public function setCourseIdentificationSystemDescriptor($course_identification_system_descriptor)
    {
        if (is_null($course_identification_system_descriptor)) {
            throw new \InvalidArgumentException('non-nullable course_identification_system_descriptor cannot be null');
        }
        if ((mb_strlen($course_identification_system_descriptor) > 306)) {
            throw new \InvalidArgumentException('invalid length for $course_identification_system_descriptor when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be smaller than or equal to 306.');
        }

        $this->container['course_identification_system_descriptor'] = $course_identification_system_descriptor;

        return $this;
    }

    /**
     * Gets assigning_organization_identification_code
     *
     * @return string|null
     */
    public function getAssigningOrganizationIdentificationCode()
    {
        return $this->container['assigning_organization_identification_code'];
    }

    /**
     * Sets assigning_organization_identification_code
     *
     * @param string|null $assigning_organization_identification_code The organization code or name assigning the Identification Code.
     *
     * @return self
     */
    public function setAssigningOrganizationIdentificationCode($assigning_organization_identification_code)
    {
        if (is_null($assigning_organization_identification_code)) {
            array_push($this->openAPINullablesSetToNull, 'assigning_organization_identification_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assigning_organization_identification_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($assigning_organization_identification_code) && (mb_strlen($assigning_organization_identification_code) > 60)) {
            throw new \InvalidArgumentException('invalid length for $assigning_organization_identification_code when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be smaller than or equal to 60.');
        }
        if (!is_null($assigning_organization_identification_code) && (mb_strlen($assigning_organization_identification_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $assigning_organization_identification_code when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be bigger than or equal to 1.');
        }

        $this->container['assigning_organization_identification_code'] = $assigning_organization_identification_code;

        return $this;
    }

    /**
     * Gets course_catalog_url
     *
     * @return string|null
     */
    public function getCourseCatalogUrl()
    {
        return $this->container['course_catalog_url'];
    }

    /**
     * Sets course_catalog_url
     *
     * @param string|null $course_catalog_url The URL for the course catalog that defines the course identification code.
     *
     * @return self
     */
    public function setCourseCatalogUrl($course_catalog_url)
    {
        if (is_null($course_catalog_url)) {
            array_push($this->openAPINullablesSetToNull, 'course_catalog_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('course_catalog_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($course_catalog_url) && (mb_strlen($course_catalog_url) > 255)) {
            throw new \InvalidArgumentException('invalid length for $course_catalog_url when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be smaller than or equal to 255.');
        }
        if (!is_null($course_catalog_url) && (mb_strlen($course_catalog_url) < 5)) {
            throw new \InvalidArgumentException('invalid length for $course_catalog_url when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be bigger than or equal to 5.');
        }

        $this->container['course_catalog_url'] = $course_catalog_url;

        return $this;
    }

    /**
     * Gets identification_code
     *
     * @return string
     */
    public function getIdentificationCode()
    {
        return $this->container['identification_code'];
    }

    /**
     * Sets identification_code
     *
     * @param string $identification_code A unique number or alphanumeric code assigned to a course by a school, school system, state, or other agency or entity. For multi-part course codes, concatenate the parts separated by a \"/\". For example, consider the following SCED code-    subject = 20 Math    course = 272 Geometry    level = G General    credits = 1.00   course sequence 1 of 1- would be entered as 20/272/G/1.00/1 of 1.
     *
     * @return self
     */
    public function setIdentificationCode($identification_code)
    {
        if (is_null($identification_code)) {
            throw new \InvalidArgumentException('non-nullable identification_code cannot be null');
        }
        if ((mb_strlen($identification_code) > 60)) {
            throw new \InvalidArgumentException('invalid length for $identification_code when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be smaller than or equal to 60.');
        }
        if ((mb_strlen($identification_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $identification_code when calling EdFiCourseTranscriptAlternativeCourseIdentificationCode., must be bigger than or equal to 1.');
        }

        $this->container['identification_code'] = $identification_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


