<?php
/**
 * TpdmEvaluation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Resources\Model;

use \ArrayAccess;
use \Resources\ObjectSerializer;

/**
 * TpdmEvaluation Class Doc Comment
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TpdmEvaluation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'tpdm_evaluation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'evaluation_title' => 'string',
        'performance_evaluation_reference' => '\Resources\Model\TpdmPerformanceEvaluationReference',
        'evaluation_description' => 'string',
        'evaluation_type_descriptor' => 'string',
        'inter_rater_reliability_score' => 'int',
        'max_rating' => 'float',
        'min_rating' => 'float',
        'rating_levels' => '\Resources\Model\TpdmEvaluationRatingLevel[]',
        '_etag' => 'string',
        '_last_modified_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'evaluation_title' => null,
        'performance_evaluation_reference' => null,
        'evaluation_description' => null,
        'evaluation_type_descriptor' => null,
        'inter_rater_reliability_score' => 'int32',
        'max_rating' => 'double',
        'min_rating' => 'double',
        'rating_levels' => null,
        '_etag' => null,
        '_last_modified_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'evaluation_title' => false,
        'performance_evaluation_reference' => false,
        'evaluation_description' => true,
        'evaluation_type_descriptor' => true,
        'inter_rater_reliability_score' => true,
        'max_rating' => true,
        'min_rating' => true,
        'rating_levels' => false,
        '_etag' => false,
        '_last_modified_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'evaluation_title' => 'evaluationTitle',
        'performance_evaluation_reference' => 'performanceEvaluationReference',
        'evaluation_description' => 'evaluationDescription',
        'evaluation_type_descriptor' => 'evaluationTypeDescriptor',
        'inter_rater_reliability_score' => 'interRaterReliabilityScore',
        'max_rating' => 'maxRating',
        'min_rating' => 'minRating',
        'rating_levels' => 'ratingLevels',
        '_etag' => '_etag',
        '_last_modified_date' => '_lastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'evaluation_title' => 'setEvaluationTitle',
        'performance_evaluation_reference' => 'setPerformanceEvaluationReference',
        'evaluation_description' => 'setEvaluationDescription',
        'evaluation_type_descriptor' => 'setEvaluationTypeDescriptor',
        'inter_rater_reliability_score' => 'setInterRaterReliabilityScore',
        'max_rating' => 'setMaxRating',
        'min_rating' => 'setMinRating',
        'rating_levels' => 'setRatingLevels',
        '_etag' => 'setEtag',
        '_last_modified_date' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'evaluation_title' => 'getEvaluationTitle',
        'performance_evaluation_reference' => 'getPerformanceEvaluationReference',
        'evaluation_description' => 'getEvaluationDescription',
        'evaluation_type_descriptor' => 'getEvaluationTypeDescriptor',
        'inter_rater_reliability_score' => 'getInterRaterReliabilityScore',
        'max_rating' => 'getMaxRating',
        'min_rating' => 'getMinRating',
        'rating_levels' => 'getRatingLevels',
        '_etag' => 'getEtag',
        '_last_modified_date' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('evaluation_title', $data ?? [], null);
        $this->setIfExists('performance_evaluation_reference', $data ?? [], null);
        $this->setIfExists('evaluation_description', $data ?? [], null);
        $this->setIfExists('evaluation_type_descriptor', $data ?? [], null);
        $this->setIfExists('inter_rater_reliability_score', $data ?? [], null);
        $this->setIfExists('max_rating', $data ?? [], null);
        $this->setIfExists('min_rating', $data ?? [], null);
        $this->setIfExists('rating_levels', $data ?? [], null);
        $this->setIfExists('_etag', $data ?? [], null);
        $this->setIfExists('_last_modified_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['evaluation_title'] === null) {
            $invalidProperties[] = "'evaluation_title' can't be null";
        }
        if ((mb_strlen($this->container['evaluation_title']) > 50)) {
            $invalidProperties[] = "invalid value for 'evaluation_title', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['evaluation_title']) < 1)) {
            $invalidProperties[] = "invalid value for 'evaluation_title', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['performance_evaluation_reference'] === null) {
            $invalidProperties[] = "'performance_evaluation_reference' can't be null";
        }
        if (!is_null($this->container['evaluation_description']) && (mb_strlen($this->container['evaluation_description']) > 255)) {
            $invalidProperties[] = "invalid value for 'evaluation_description', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['evaluation_type_descriptor']) && (mb_strlen($this->container['evaluation_type_descriptor']) > 306)) {
            $invalidProperties[] = "invalid value for 'evaluation_type_descriptor', the character length must be smaller than or equal to 306.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id 
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets evaluation_title
     *
     * @return string
     */
    public function getEvaluationTitle()
    {
        return $this->container['evaluation_title'];
    }

    /**
     * Sets evaluation_title
     *
     * @param string $evaluation_title The name or title of the evaluation.
     *
     * @return self
     */
    public function setEvaluationTitle($evaluation_title)
    {
        if (is_null($evaluation_title)) {
            throw new \InvalidArgumentException('non-nullable evaluation_title cannot be null');
        }
        if ((mb_strlen($evaluation_title) > 50)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_title when calling TpdmEvaluation., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($evaluation_title) < 1)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_title when calling TpdmEvaluation., must be bigger than or equal to 1.');
        }

        $this->container['evaluation_title'] = $evaluation_title;

        return $this;
    }

    /**
     * Gets performance_evaluation_reference
     *
     * @return \Resources\Model\TpdmPerformanceEvaluationReference
     */
    public function getPerformanceEvaluationReference()
    {
        return $this->container['performance_evaluation_reference'];
    }

    /**
     * Sets performance_evaluation_reference
     *
     * @param \Resources\Model\TpdmPerformanceEvaluationReference $performance_evaluation_reference performance_evaluation_reference
     *
     * @return self
     */
    public function setPerformanceEvaluationReference($performance_evaluation_reference)
    {
        if (is_null($performance_evaluation_reference)) {
            throw new \InvalidArgumentException('non-nullable performance_evaluation_reference cannot be null');
        }
        $this->container['performance_evaluation_reference'] = $performance_evaluation_reference;

        return $this;
    }

    /**
     * Gets evaluation_description
     *
     * @return string|null
     */
    public function getEvaluationDescription()
    {
        return $this->container['evaluation_description'];
    }

    /**
     * Sets evaluation_description
     *
     * @param string|null $evaluation_description The long description of the Evaluation.
     *
     * @return self
     */
    public function setEvaluationDescription($evaluation_description)
    {
        if (is_null($evaluation_description)) {
            array_push($this->openAPINullablesSetToNull, 'evaluation_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('evaluation_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($evaluation_description) && (mb_strlen($evaluation_description) > 255)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_description when calling TpdmEvaluation., must be smaller than or equal to 255.');
        }

        $this->container['evaluation_description'] = $evaluation_description;

        return $this;
    }

    /**
     * Gets evaluation_type_descriptor
     *
     * @return string|null
     */
    public function getEvaluationTypeDescriptor()
    {
        return $this->container['evaluation_type_descriptor'];
    }

    /**
     * Sets evaluation_type_descriptor
     *
     * @param string|null $evaluation_type_descriptor The type of the evaluation (e.g., observation, principal, peer, student survey, student growth).
     *
     * @return self
     */
    public function setEvaluationTypeDescriptor($evaluation_type_descriptor)
    {
        if (is_null($evaluation_type_descriptor)) {
            array_push($this->openAPINullablesSetToNull, 'evaluation_type_descriptor');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('evaluation_type_descriptor', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($evaluation_type_descriptor) && (mb_strlen($evaluation_type_descriptor) > 306)) {
            throw new \InvalidArgumentException('invalid length for $evaluation_type_descriptor when calling TpdmEvaluation., must be smaller than or equal to 306.');
        }

        $this->container['evaluation_type_descriptor'] = $evaluation_type_descriptor;

        return $this;
    }

    /**
     * Gets inter_rater_reliability_score
     *
     * @return int|null
     */
    public function getInterRaterReliabilityScore()
    {
        return $this->container['inter_rater_reliability_score'];
    }

    /**
     * Sets inter_rater_reliability_score
     *
     * @param int|null $inter_rater_reliability_score A score indicating how much homogeneity, or consensus, there is in the ratings given by judges. Most commonly a percentage scale (1-100)
     *
     * @return self
     */
    public function setInterRaterReliabilityScore($inter_rater_reliability_score)
    {
        if (is_null($inter_rater_reliability_score)) {
            array_push($this->openAPINullablesSetToNull, 'inter_rater_reliability_score');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inter_rater_reliability_score', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inter_rater_reliability_score'] = $inter_rater_reliability_score;

        return $this;
    }

    /**
     * Gets max_rating
     *
     * @return float|null
     */
    public function getMaxRating()
    {
        return $this->container['max_rating'];
    }

    /**
     * Sets max_rating
     *
     * @param float|null $max_rating The maximum summary numerical rating or score for the evaluation.
     *
     * @return self
     */
    public function setMaxRating($max_rating)
    {
        if (is_null($max_rating)) {
            array_push($this->openAPINullablesSetToNull, 'max_rating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_rating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_rating'] = $max_rating;

        return $this;
    }

    /**
     * Gets min_rating
     *
     * @return float|null
     */
    public function getMinRating()
    {
        return $this->container['min_rating'];
    }

    /**
     * Sets min_rating
     *
     * @param float|null $min_rating The minimum summary numerical rating or score for the evaluation. If omitted, assumed to be 0.0.
     *
     * @return self
     */
    public function setMinRating($min_rating)
    {
        if (is_null($min_rating)) {
            array_push($this->openAPINullablesSetToNull, 'min_rating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_rating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_rating'] = $min_rating;

        return $this;
    }

    /**
     * Gets rating_levels
     *
     * @return \Resources\Model\TpdmEvaluationRatingLevel[]|null
     */
    public function getRatingLevels()
    {
        return $this->container['rating_levels'];
    }

    /**
     * Sets rating_levels
     *
     * @param \Resources\Model\TpdmEvaluationRatingLevel[]|null $rating_levels An unordered collection of evaluationRatingLevels. The descriptive level(s) of ratings (cut scores) for the evaluation.
     *
     * @return self
     */
    public function setRatingLevels($rating_levels)
    {
        if (is_null($rating_levels)) {
            throw new \InvalidArgumentException('non-nullable rating_levels cannot be null');
        }
        $this->container['rating_levels'] = $rating_levels;

        return $this;
    }

    /**
     * Gets _etag
     *
     * @return string|null
     */
    public function getEtag()
    {
        return $this->container['_etag'];
    }

    /**
     * Sets _etag
     *
     * @param string|null $_etag A unique system-generated value that identifies the version of the resource.
     *
     * @return self
     */
    public function setEtag($_etag)
    {
        if (is_null($_etag)) {
            throw new \InvalidArgumentException('non-nullable _etag cannot be null');
        }
        $this->container['_etag'] = $_etag;

        return $this;
    }

    /**
     * Gets _last_modified_date
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['_last_modified_date'];
    }

    /**
     * Sets _last_modified_date
     *
     * @param \DateTime|null $_last_modified_date The date and time the resource was last modified.
     *
     * @return self
     */
    public function setLastModifiedDate($_last_modified_date)
    {
        if (is_null($_last_modified_date)) {
            throw new \InvalidArgumentException('non-nullable _last_modified_date cannot be null');
        }
        $this->container['_last_modified_date'] = $_last_modified_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


