<?php
/**
 * TrackedChangesEdFiSurveySectionResponseKey
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TrackedChangesEdFiSurveySectionResponseKey Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrackedChangesEdFiSurveySectionResponseKey implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'trackedChanges_edFi_surveySectionResponseKey';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'namespace' => 'string',
        'survey_identifier' => 'string',
        'survey_response_identifier' => 'string',
        'survey_section_title' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'namespace' => null,
        'survey_identifier' => null,
        'survey_response_identifier' => null,
        'survey_section_title' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'namespace' => false,
        'survey_identifier' => false,
        'survey_response_identifier' => false,
        'survey_section_title' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'namespace' => 'namespace',
        'survey_identifier' => 'surveyIdentifier',
        'survey_response_identifier' => 'surveyResponseIdentifier',
        'survey_section_title' => 'surveySectionTitle'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'namespace' => 'setNamespace',
        'survey_identifier' => 'setSurveyIdentifier',
        'survey_response_identifier' => 'setSurveyResponseIdentifier',
        'survey_section_title' => 'setSurveySectionTitle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'namespace' => 'getNamespace',
        'survey_identifier' => 'getSurveyIdentifier',
        'survey_response_identifier' => 'getSurveyResponseIdentifier',
        'survey_section_title' => 'getSurveySectionTitle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('namespace', $data ?? [], null);
        $this->setIfExists('survey_identifier', $data ?? [], null);
        $this->setIfExists('survey_response_identifier', $data ?? [], null);
        $this->setIfExists('survey_section_title', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['namespace']) && (mb_strlen($this->container['namespace']) > 255)) {
            $invalidProperties[] = "invalid value for 'namespace', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['namespace']) && (mb_strlen($this->container['namespace']) < 5)) {
            $invalidProperties[] = "invalid value for 'namespace', the character length must be bigger than or equal to 5.";
        }

        if (!is_null($this->container['survey_identifier']) && (mb_strlen($this->container['survey_identifier']) > 60)) {
            $invalidProperties[] = "invalid value for 'survey_identifier', the character length must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['survey_identifier']) && (mb_strlen($this->container['survey_identifier']) < 1)) {
            $invalidProperties[] = "invalid value for 'survey_identifier', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['survey_response_identifier']) && (mb_strlen($this->container['survey_response_identifier']) > 60)) {
            $invalidProperties[] = "invalid value for 'survey_response_identifier', the character length must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['survey_response_identifier']) && (mb_strlen($this->container['survey_response_identifier']) < 1)) {
            $invalidProperties[] = "invalid value for 'survey_response_identifier', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['survey_section_title']) && (mb_strlen($this->container['survey_section_title']) > 255)) {
            $invalidProperties[] = "invalid value for 'survey_section_title', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['survey_section_title']) && (mb_strlen($this->container['survey_section_title']) < 1)) {
            $invalidProperties[] = "invalid value for 'survey_section_title', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets namespace
     *
     * @return string|null
     */
    public function getNamespace()
    {
        return $this->container['namespace'];
    }

    /**
     * Sets namespace
     *
     * @param string|null $namespace Namespace for the survey.
     *
     * @return self
     */
    public function setNamespace($namespace)
    {
        if (is_null($namespace)) {
            throw new \InvalidArgumentException('non-nullable namespace cannot be null');
        }
        if ((mb_strlen($namespace) > 255)) {
            throw new \InvalidArgumentException('invalid length for $namespace when calling TrackedChangesEdFiSurveySectionResponseKey., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($namespace) < 5)) {
            throw new \InvalidArgumentException('invalid length for $namespace when calling TrackedChangesEdFiSurveySectionResponseKey., must be bigger than or equal to 5.');
        }

        $this->container['namespace'] = $namespace;

        return $this;
    }

    /**
     * Gets survey_identifier
     *
     * @return string|null
     */
    public function getSurveyIdentifier()
    {
        return $this->container['survey_identifier'];
    }

    /**
     * Sets survey_identifier
     *
     * @param string|null $survey_identifier The unique survey identifier from the survey tool.
     *
     * @return self
     */
    public function setSurveyIdentifier($survey_identifier)
    {
        if (is_null($survey_identifier)) {
            throw new \InvalidArgumentException('non-nullable survey_identifier cannot be null');
        }
        if ((mb_strlen($survey_identifier) > 60)) {
            throw new \InvalidArgumentException('invalid length for $survey_identifier when calling TrackedChangesEdFiSurveySectionResponseKey., must be smaller than or equal to 60.');
        }
        if ((mb_strlen($survey_identifier) < 1)) {
            throw new \InvalidArgumentException('invalid length for $survey_identifier when calling TrackedChangesEdFiSurveySectionResponseKey., must be bigger than or equal to 1.');
        }

        $this->container['survey_identifier'] = $survey_identifier;

        return $this;
    }

    /**
     * Gets survey_response_identifier
     *
     * @return string|null
     */
    public function getSurveyResponseIdentifier()
    {
        return $this->container['survey_response_identifier'];
    }

    /**
     * Sets survey_response_identifier
     *
     * @param string|null $survey_response_identifier The identifier of the survey typically from the survey application.
     *
     * @return self
     */
    public function setSurveyResponseIdentifier($survey_response_identifier)
    {
        if (is_null($survey_response_identifier)) {
            throw new \InvalidArgumentException('non-nullable survey_response_identifier cannot be null');
        }
        if ((mb_strlen($survey_response_identifier) > 60)) {
            throw new \InvalidArgumentException('invalid length for $survey_response_identifier when calling TrackedChangesEdFiSurveySectionResponseKey., must be smaller than or equal to 60.');
        }
        if ((mb_strlen($survey_response_identifier) < 1)) {
            throw new \InvalidArgumentException('invalid length for $survey_response_identifier when calling TrackedChangesEdFiSurveySectionResponseKey., must be bigger than or equal to 1.');
        }

        $this->container['survey_response_identifier'] = $survey_response_identifier;

        return $this;
    }

    /**
     * Gets survey_section_title
     *
     * @return string|null
     */
    public function getSurveySectionTitle()
    {
        return $this->container['survey_section_title'];
    }

    /**
     * Sets survey_section_title
     *
     * @param string|null $survey_section_title The title or label for the survey section.
     *
     * @return self
     */
    public function setSurveySectionTitle($survey_section_title)
    {
        if (is_null($survey_section_title)) {
            throw new \InvalidArgumentException('non-nullable survey_section_title cannot be null');
        }
        if ((mb_strlen($survey_section_title) > 255)) {
            throw new \InvalidArgumentException('invalid length for $survey_section_title when calling TrackedChangesEdFiSurveySectionResponseKey., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($survey_section_title) < 1)) {
            throw new \InvalidArgumentException('invalid length for $survey_section_title when calling TrackedChangesEdFiSurveySectionResponseKey., must be bigger than or equal to 1.');
        }

        $this->container['survey_section_title'] = $survey_section_title;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


