<?php
/**
 * EdFiStudentEducationOrganizationAssociationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Resources\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EdFiStudentEducationOrganizationAssociationTest Class Doc Comment
 *
 * @category    Class
 * @description EdFiStudentEducationOrganizationAssociation
 * @package     Resources
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EdFiStudentEducationOrganizationAssociationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EdFiStudentEducationOrganizationAssociation"
     */
    public function testEdFiStudentEducationOrganizationAssociation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "education_organization_reference"
     */
    public function testPropertyEducationOrganizationReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "student_reference"
     */
    public function testPropertyStudentReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ancestry_ethnic_origins"
     */
    public function testPropertyAncestryEthnicOrigins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "barrier_to_internet_access_in_residence_descriptor"
     */
    public function testPropertyBarrierToInternetAccessInResidenceDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cohort_years"
     */
    public function testPropertyCohortYears()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "disabilities"
     */
    public function testPropertyDisabilities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "electronic_mails"
     */
    public function testPropertyElectronicMails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gender_identity"
     */
    public function testPropertyGenderIdentity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hispanic_latino_ethnicity"
     */
    public function testPropertyHispanicLatinoEthnicity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "international_addresses"
     */
    public function testPropertyInternationalAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "internet_access_in_residence"
     */
    public function testPropertyInternetAccessInResidence()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "internet_access_type_in_residence_descriptor"
     */
    public function testPropertyInternetAccessTypeInResidenceDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "internet_performance_in_residence_descriptor"
     */
    public function testPropertyInternetPerformanceInResidenceDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "limited_english_proficiency_descriptor"
     */
    public function testPropertyLimitedEnglishProficiencyDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "login_id"
     */
    public function testPropertyLoginId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_learning_device_access_descriptor"
     */
    public function testPropertyPrimaryLearningDeviceAccessDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_learning_device_away_from_school_descriptor"
     */
    public function testPropertyPrimaryLearningDeviceAwayFromSchoolDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_learning_device_provider_descriptor"
     */
    public function testPropertyPrimaryLearningDeviceProviderDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "profile_thumbnail"
     */
    public function testPropertyProfileThumbnail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "races"
     */
    public function testPropertyRaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sex_descriptor"
     */
    public function testPropertySexDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "student_characteristics"
     */
    public function testPropertyStudentCharacteristics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "student_identification_codes"
     */
    public function testPropertyStudentIdentificationCodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "student_indicators"
     */
    public function testPropertyStudentIndicators()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "supporter_military_connection_descriptor"
     */
    public function testPropertySupporterMilitaryConnectionDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "telephones"
     */
    public function testPropertyTelephones()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tribal_affiliations"
     */
    public function testPropertyTribalAffiliations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "_etag"
     */
    public function testPropertyEtag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "_last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
