<?php
/**
 * BalanceSheetDimensionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BalanceSheetDimensionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BalanceSheetDimensionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteBalanceSheetDimensionById
     *
     * Deletes an existing resource using the resource identifier..
     *
     */
    public function testDeleteBalanceSheetDimensionById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletesBalanceSheetDimensions
     *
     * Retrieves deleted resources based on change version..
     *
     */
    public function testDeletesBalanceSheetDimensions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBalanceSheetDimensions
     *
     * Retrieves specific resources using the resource's property values (using the \"Get\" pattern)..
     *
     */
    public function testGetBalanceSheetDimensions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBalanceSheetDimensionsById
     *
     * Retrieves a specific resource using the resource's identifier (using the \"Get By Id\" pattern)..
     *
     */
    public function testGetBalanceSheetDimensionsById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for keyChangesBalanceSheetDimensions
     *
     * Retrieves resources key changes based on change version..
     *
     */
    public function testKeyChangesBalanceSheetDimensions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBalanceSheetDimension
     *
     * Creates or updates resources based on the natural key values of the supplied resource..
     *
     */
    public function testPostBalanceSheetDimension()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putBalanceSheetDimension
     *
     * Updates a resource based on the resource identifier..
     *
     */
    public function testPutBalanceSheetDimension()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
