<?php
/**
 * SurveyResponseEducationOrganizationTargetAssociationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Resources\Test\Api;

use \Resources\Configuration;
use \Resources\ApiException;
use \Resources\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SurveyResponseEducationOrganizationTargetAssociationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Resources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SurveyResponseEducationOrganizationTargetAssociationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSurveyResponseEducationOrganizationTargetAssociationById
     *
     * Deletes an existing resource using the resource identifier..
     *
     */
    public function testDeleteSurveyResponseEducationOrganizationTargetAssociationById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletesSurveyResponseEducationOrganizationTargetAssociations
     *
     * Retrieves deleted resources based on change version..
     *
     */
    public function testDeletesSurveyResponseEducationOrganizationTargetAssociations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSurveyResponseEducationOrganizationTargetAssociations
     *
     * Retrieves specific resources using the resource's property values (using the \"Get\" pattern)..
     *
     */
    public function testGetSurveyResponseEducationOrganizationTargetAssociations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSurveyResponseEducationOrganizationTargetAssociationsById
     *
     * Retrieves a specific resource using the resource's identifier (using the \"Get By Id\" pattern)..
     *
     */
    public function testGetSurveyResponseEducationOrganizationTargetAssociationsById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for keyChangesSurveyResponseEducationOrganizationTargetAssociations
     *
     * Retrieves resources key changes based on change version..
     *
     */
    public function testKeyChangesSurveyResponseEducationOrganizationTargetAssociations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSurveyResponseEducationOrganizationTargetAssociation
     *
     * Creates or updates resources based on the natural key values of the supplied resource..
     *
     */
    public function testPostSurveyResponseEducationOrganizationTargetAssociation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putSurveyResponseEducationOrganizationTargetAssociation
     *
     * Updates a resource based on the resource identifier..
     *
     */
    public function testPutSurveyResponseEducationOrganizationTargetAssociation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
